### ISSUE TITLE
Could not find code source for magic-at

### ISSUE THREAD

**Issue by silentnyte** [LordDeatHunter/HarvestScythes#28] opened 2022-01-25 19:26 UTC
Could not find code source for magic-at:/net/minecraft/class_1886$15.class: java.net.MalformedURLException: unknown protocol: magic-at
Could not find code source for magic-at:/net/minecraft/class_1886$16.class: java.net.MalformedURLException: unknown protocol: magic-at

Minecraft - 1.18.1
Fabric loader - 0.12.12
Fabric API - 0.46.1+1.18
Harvest Scythes - 2.4.1

https://paste.ee/p/fqtTR

**Comment by LordDeatHunter** [comment] 2022-01-25 20:12
It seems to be an incompatibility issue caused by some other mod, as I've had no issues with the latest version of Harvest Scythes.
Look into mods that add new types of tools.

**Comment by silentnyte** [comment] 2022-01-25 20:23
The mods that I listed are the only ones that I have enabled.

**Comment by LordDeatHunter** [comment] 2022-01-25 20:44
Try reinstalling/updating your mods?

**Comment by silentnyte** [comment] 2022-01-25 20:56
I created a new instance in MultiMC and only loaded Fabric API and HC and I get the same error.

https://paste.ee/p/wL5gw

**Comment by pewblaze** [comment] 2022-04-29 23:17
Hi i get the same error. Tracked it down to this. 
It started after updating the Fabric Modloader from 0.13.3 to 0.14.3
https://gist.github.com/pewblaze/96283ea0aa9f1805104c0fe7666132a2

**Comment by MrLavender** [comment] 2022-05-02 03:22
I can replicate the same crash with just;

Minecraft 1.18.2
Fabric Loader 0.14.3
Fabric API 0.51.1+1.18.2
harvest_scythes 2.5.0

Upgrading Fabric Loader to 0.14.4 fixes the crash. Because of this commit I guess...

https://github.com/FabricMC/fabric-loader/commit/52d6dc0ba80addc61e08d4740f015cc383d26153

**Comment by MrLavender** [comment] 2022-05-02 15:16
> So, updating to latest Fabric no longer causes this issue?

Yes, this issue is fixed by using Fabric Loader >= 0.14.4

**Closed** 2022-05-02 15:27 UTC
